# Generated by Django 4.2.3 on 2023-08-14 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_tokenmodel_token"),
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tgusermodel",
            name="token",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tg_user",
                to="api.tokenmodel",
            ),
        ),
    ]
