version: '3.8'

services:
  service:
    build:
      context: .
      dockerfile: ./service.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10

  bot:
    build:
      context: .
      dockerfile: ./bot.Dockerfile
    # ports:
    #   - "8001:8001"
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10

  db:
    image: postgres:15.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    # ports:
    #  - "5432:5432"
    # expose:
    #  - 5432

volumes:
  postgres_data:
